# Generated by Django 4.1.1 on 2022-09-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapiapp', '0002_checklist_checklistitem_delete_student_admission'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='checklistitem',
            name='checklist',
        ),
        migrations.DeleteModel(
            name='CheckList',
        ),
        migrations.DeleteModel(
            name='CheckListItem',
        ),
    ]
