# Generated by Django 4.1.1 on 2022-09-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapiapp', '0003_user_remove_checklistitem_checklist_delete_checklist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='title',
            new_name='age',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
